### ISSUE TITLE
Missing skeleton file when trying to generate the .java source file

### ISSUE THREAD

**Issue by joelmoniz** [bobbylight/TokenMakerMaker#6] opened 2015-08-14 19:32 UTC
Trying to generate the .java source file throws the following error:

```
Generating JFlex source...

Generating Java source...
Command: "C:\Program Files\Java\jre1.8.0_31\bin\java.exe" "-cp" "C:\Users\Joel\Documents\Code\p5\TokenMakerMaker\build\install\tmm\jflex-1.4.1.jar" "JFlex.Main" "C:\Users\Joel\Documents\Code\p5\TMMOutput\processing\app\rsta\PDESyntaxHighlight.flex" "-d" "C:\Users\Joel\Documents\Code\p5\TMMOutput\processing\app\rsta" "--skel" "C:\Users\Joel\Documents\Code\p5\TokenMakerMaker\build\install\tmm\src\main\dist\skeleton.default"

Error: Cannot read skeleton file "C:\Users\Joel\Documents\Code\p5\TokenMakerMaker\build\install\tmm\src\main\dist\skeleton.default".
1 error, 0 warnings.
Exited with rc: 1

Cannot continue due to previous errors! If you believe this is a bug in the
application (and it likely is), please report it at: https://github.com/bobbylight/TokenMakerMaker/issues
```

NB: Checking out the path that is described in the error, I can't seem to find the `skeleton.default` file. Do I need to add it in from somewhere?

**Comment by bobbylight** [comment] 2015-08-15 05:16
Sounds like a bug, but I cannot reproduce it.  How are you building and running, and on what OS?  Something like this works for me:

    gradlew installDist
    cd build\install\tmm
    java -jar tmm.jar

I think there is a bug with determining the application's root folder on OS X, but I'm not sure if that's what you're running into or not.

**Comment by joelmoniz** [comment] 2015-08-15 08:27
I'm on Windows 8.1. I used the same set of commands as you provided (but a `gradlew clean build install`). The TMM window displays fine, but I get the error when trying to generate.

I managed to fix this by adding in [this](https://github.com/ghostandthemachine/rsyntaxtextarea/blob/master/TokenMakerMaker/trunk/res/skeleton.default) file at `TokenMakerMaker\src\main\dist`, so perhaps the file hasn't been committed and pushed (or was accidentally removed from the repo at some point)?

**Comment by joelmoniz** [comment] 2015-08-15 08:31
So I quickly looked into this, and I think this file might have been deleted (or, more likely, renamed, but only the deletion committed) in [this](https://github.com/bobbylight/TokenMakerMaker/commit/d41616e878b490ea7504caa05f09290b04a8d152) commit. I've filed a PR to add back this file.

**Comment by DestroyerPlays** [comment] 2017-07-17 02:33
Could any of you please give me a link to a JAR you generated if you still have any. Thanks.

**Comment by bobbylight** [comment] 2019-12-31 03:47
Finally cleaning this project up, albeit several years too late.  These issues should be resolved now, so I'm closing this ticket.

**Closed by bobbylight** 2019-12-31 03:47 UTC
